# password
password: Test@123

server:
  applicationConnectors:
    - type: http
      port: 8080

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: root
  url: jdbc:mysql://localhost:3306/bookmarks